// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210514194902_UserId")]
    partial class UserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("adversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("dtAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dtCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("psnAdversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("telefoneAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoJogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 1,
                            adversario = "Tombense",
                            data = "15-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 705, DateTimeKind.Local).AddTicks(8297),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 705, DateTimeKind.Local).AddTicks(8312),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 2,
                            TeamId = 1,
                            adversario = "America",
                            data = "14-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8603),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8605),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 3,
                            TeamId = 1,
                            adversario = "Cruzeiro",
                            data = "14-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8750),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8752),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 4,
                            TeamId = 2,
                            adversario = "Tombense",
                            data = "18-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8772),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8774),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 5,
                            TeamId = 2,
                            adversario = "America",
                            data = "16-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8793),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8795),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 6,
                            TeamId = 2,
                            adversario = "Cruzeiro",
                            data = "16-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8822),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8823),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 7,
                            TeamId = 3,
                            adversario = "Tombense",
                            data = "15-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8843),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8845),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 8,
                            TeamId = 3,
                            adversario = "America",
                            data = "17-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8864),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8866),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 9,
                            TeamId = 3,
                            adversario = "Cruzeiro",
                            data = "17-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8886),
                            dataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 706, DateTimeKind.Local).AddTicks(8888),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PerfilPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PlayerAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("PosicaoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoP")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 708, DateTimeKind.Local).AddTicks(1247),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 708, DateTimeKind.Local).AddTicks(1232),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maykon",
                            Numero = 13,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "Maykon1993",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2376),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2365),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Samuel",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "santacruzpe",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2578),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2575),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Celio",
                            Numero = 99,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "Celio_Shadow_14",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2603),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2601),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jose",
                            Numero = 3,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "joselito1970",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2619),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2617),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mauricio",
                            Numero = 4,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Goleiro",
                            Psn = "maumau",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2643),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2641),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando",
                            Numero = 6,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Meia Atacante",
                            Psn = "fernando123",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2658),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2656),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Adam",
                            Numero = 2,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Zagueiro",
                            Psn = "adao",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2674),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2672),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Emerson",
                            Numero = 5,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Atacante",
                            PosicaoP = "Volante",
                            Psn = "emer",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2689),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 709, DateTimeKind.Local).AddTicks(2687),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jullius",
                            Numero = 9,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "agueiro",
                            PosicaoP = "Atacante",
                            Psn = "cachaca",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuraTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayersApp");
                });

            modelBuilder.Entity("Dominio.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GamePes")
                        .HasColumnType("bit");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("TimeAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 695, DateTimeKind.Local).AddTicks(1148),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 701, DateTimeKind.Local).AddTicks(5234),
                            DataFundacao = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3249),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3431),
                            DataFundacao = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3534),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3559),
                            DataFundacao = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 4,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3565),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3578),
                            DataFundacao = new DateTime(1924, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "cruzeirocaiu.jpg",
                            NomeTime = "Cruzeiro",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 5,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3583),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 702, DateTimeKind.Local).AddTicks(3591),
                            DataFundacao = new DateTime(1908, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "galaodamassa.jpg",
                            NomeTime = "Atletico",
                            TimeAtivo = true
                        });
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(2477),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(2463),
                            Email = "maykontaiorpm@gmail.com",
                            Login = "Maykon1993",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(6356),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(6343),
                            Email = "belbelm@gmail.com",
                            Login = "belcastroic",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(6404),
                            DataCadastro = new DateTime(2021, 5, 14, 16, 49, 0, 707, DateTimeKind.Local).AddTicks(6402),
                            Email = "santacruz@gmail.com",
                            Login = "santacruzpe451",
                            Senha = "teste@123"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Games")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("Dominio.Models.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("Dominio.Models.Player", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
