// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210426105603_Sem Posicao")]
    partial class SemPosicao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PerfilPlayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PlayerAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Psn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 318, DateTimeKind.Local).AddTicks(94),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 318, DateTimeKind.Local).AddTicks(7639),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maykon",
                            Numero = 13,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = false,
                            Psn = "Maykon1993",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(3556),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(3788),
                            DataNascimento = new DateTime(2000, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Samuel",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            Psn = "santacruzpe",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4029),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4078),
                            DataNascimento = new DateTime(1989, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Celio",
                            Numero = 9,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            Psn = "Celio_Shadow_14",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4088),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4113),
                            DataNascimento = new DateTime(1978, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jose",
                            Numero = 5,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            Psn = "joselito1970",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4122),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4144),
                            DataNascimento = new DateTime(1990, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mauricio",
                            Numero = 6,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            Psn = "maumau",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4169),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4190),
                            DataNascimento = new DateTime(1980, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando",
                            Numero = 10,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = false,
                            Psn = "fernando123",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4197),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4216),
                            DataNascimento = new DateTime(1994, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Adam",
                            Numero = 2,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            Psn = "adao",
                            TimeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4225),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4246),
                            DataNascimento = new DateTime(1998, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Emerson",
                            Numero = 8,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = false,
                            Psn = "emer",
                            TimeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4253),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 320, DateTimeKind.Local).AddTicks(4273),
                            DataNascimento = new DateTime(1988, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jullius",
                            Numero = 3,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            Psn = "cachaca",
                            TimeId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuraTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("PlayersApp");
                });

            modelBuilder.Entity("Dominio.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TimeAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 306, DateTimeKind.Local).AddTicks(6836),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 314, DateTimeKind.Local).AddTicks(7121),
                            DataFundacao = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 315, DateTimeKind.Local).AddTicks(4156),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 315, DateTimeKind.Local).AddTicks(4315),
                            DataFundacao = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 4, 26, 7, 56, 2, 315, DateTimeKind.Local).AddTicks(4395),
                            DataCadastro = new DateTime(2021, 4, 26, 7, 56, 2, 315, DateTimeKind.Local).AddTicks(4418),
                            DataFundacao = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq",
                            TimeAtivo = false
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Time", "Time")
                        .WithMany("Players")
                        .HasForeignKey("TimeId");
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.HasOne("Dominio.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
