// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210505141357_campocelular")]
    partial class campocelular
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("adversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("dtAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dtCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("psnAdversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("telefoneAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoJogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 1,
                            adversario = "Tombense",
                            data = "06-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 376, DateTimeKind.Local).AddTicks(7205),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 376, DateTimeKind.Local).AddTicks(7221),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 2,
                            TeamId = 1,
                            adversario = "America",
                            data = "05-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(6977),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(6980),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 3,
                            TeamId = 1,
                            adversario = "Cruzeiro",
                            data = "05-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7139),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7140),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 4,
                            TeamId = 2,
                            adversario = "Tombense",
                            data = "09-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7164),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7166),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 5,
                            TeamId = 2,
                            adversario = "America",
                            data = "07-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7187),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7188),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 6,
                            TeamId = 2,
                            adversario = "Cruzeiro",
                            data = "07-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7225),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7227),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 7,
                            TeamId = 3,
                            adversario = "Tombense",
                            data = "06-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7246),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7248),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 8,
                            TeamId = 3,
                            adversario = "America",
                            data = "08-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7267),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7269),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 9,
                            TeamId = 3,
                            adversario = "Cruzeiro",
                            data = "08-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7289),
                            dataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 377, DateTimeKind.Local).AddTicks(7291),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PerfilPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PlayerAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("PosicaoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoP")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(8974),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(8960),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotomaykon.png",
                            Nome = "Maykon",
                            Numero = 13,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "Maykon1993",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9604),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9581),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotosamuel.png",
                            Nome = "Samuel",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "santacruzpe",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9813),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9809),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotocelio.png",
                            Nome = "Celio",
                            Numero = 99,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "Celio_Shadow_14",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9835),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9832),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotojose.png",
                            Nome = "Jose",
                            Numero = 3,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "joselito1970",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9849),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9847),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotomauricio.png",
                            Nome = "Mauricio",
                            Numero = 4,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Goleiro",
                            Psn = "maumau",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9873),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9870),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotofernando.png",
                            Nome = "Fernando",
                            Numero = 6,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Meia Atacante",
                            Psn = "fernando123",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9887),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9884),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotoadam.png",
                            Nome = "Adam",
                            Numero = 2,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Zagueiro",
                            Psn = "adao",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9900),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9898),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotoemerson.png",
                            Nome = "Emerson",
                            Numero = 5,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Atacante",
                            PosicaoP = "Volante",
                            Psn = "emer",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9913),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 379, DateTimeKind.Local).AddTicks(9911),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotojullius.png",
                            Nome = "Jullius",
                            Numero = 9,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "agueiro",
                            PosicaoP = "Atacante",
                            Psn = "cachaca",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuraTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayersApp");
                });

            modelBuilder.Entity("Dominio.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GamePes")
                        .HasColumnType("bit");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("TimeAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 367, DateTimeKind.Local).AddTicks(6875),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 372, DateTimeKind.Local).AddTicks(4633),
                            DataFundacao = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2450),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2692),
                            DataFundacao = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2785),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2808),
                            DataFundacao = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 4,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2814),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2827),
                            DataFundacao = new DateTime(1924, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "cruzeirocaiu.jpg",
                            NomeTime = "Cruzeiro",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 5,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2832),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 373, DateTimeKind.Local).AddTicks(2842),
                            DataFundacao = new DateTime(1908, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "galaodamassa.jpg",
                            NomeTime = "Atletico",
                            TimeAtivo = true
                        });
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(702),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(688),
                            Email = "maykontaiorpm@gmail.com",
                            Login = "Maykon1993",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(4572),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(4559),
                            Email = "belbelm@gmail.com",
                            Login = "belcastroic",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(4642),
                            DataCadastro = new DateTime(2021, 5, 5, 11, 13, 56, 378, DateTimeKind.Local).AddTicks(4639),
                            Email = "santacruz@gmail.com",
                            Login = "santacruzpe451",
                            Senha = "teste@123"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Games")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.HasOne("Dominio.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
