// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210503194027_cargainicialplayer")]
    partial class cargainicialplayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("adversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("dtAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dtCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("psnAdversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("telefoneAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoJogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 1,
                            adversario = "Tombense",
                            data = "04-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 190, DateTimeKind.Local).AddTicks(5003),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 190, DateTimeKind.Local).AddTicks(5016),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 2,
                            TeamId = 1,
                            adversario = "America",
                            data = "03-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5715),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5720),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 3,
                            TeamId = 1,
                            adversario = "Cruzeiro",
                            data = "03-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5959),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5962),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 4,
                            TeamId = 2,
                            adversario = "Tombense",
                            data = "07-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5994),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(5997),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 5,
                            TeamId = 2,
                            adversario = "America",
                            data = "05-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6025),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6028),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 6,
                            TeamId = 2,
                            adversario = "Cruzeiro",
                            data = "05-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6075),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6078),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 7,
                            TeamId = 3,
                            adversario = "Tombense",
                            data = "04-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6108),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6111),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 8,
                            TeamId = 3,
                            adversario = "America",
                            data = "06-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6138),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6141),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 9,
                            TeamId = 3,
                            adversario = "Cruzeiro",
                            data = "06-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6169),
                            dataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 191, DateTimeKind.Local).AddTicks(6172),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PerfilPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PlayerAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("PosicaoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoP")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 193, DateTimeKind.Local).AddTicks(3624),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 193, DateTimeKind.Local).AddTicks(3608),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotomaykon.png",
                            Nome = "Maykon",
                            Numero = 13,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "Maykon1993",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(302),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(276),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotosamuel.png",
                            Nome = "Samuel",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "santacruzpe",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(523),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(520),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotocelio.png",
                            Nome = "Celio",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "Celio_Shadow_14",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(544),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(542),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotojose.png",
                            Nome = "Jose",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "joselito1970",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(558),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(556),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotomauricio.png",
                            Nome = "Mauricio",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Goleiro",
                            Psn = "maumau",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(582),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(580),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotofernando.png",
                            Nome = "Fernando",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Meia Atacante",
                            Psn = "fernando123",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(595),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(593),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotoadam.png",
                            Nome = "Adam",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Zagueiro",
                            Psn = "adao",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(608),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(606),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotoemerson.png",
                            Nome = "Emerson",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Atacante",
                            PosicaoP = "Volante",
                            Psn = "emer",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(621),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 195, DateTimeKind.Local).AddTicks(619),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoURL = "fotojullius.png",
                            Nome = "Jullius",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "agueiro",
                            PosicaoP = "Atacante",
                            Psn = "cachaca",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuraTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayersApp");
                });

            modelBuilder.Entity("Dominio.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GamePes")
                        .HasColumnType("bit");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("TimeAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 180, DateTimeKind.Local).AddTicks(3404),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 186, DateTimeKind.Local).AddTicks(1896),
                            DataFundacao = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 186, DateTimeKind.Local).AddTicks(9722),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 186, DateTimeKind.Local).AddTicks(9931),
                            DataFundacao = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(39),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(64),
                            DataFundacao = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 4,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(71),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(84),
                            DataFundacao = new DateTime(1924, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "cruzeirocaiu.jpg",
                            NomeTime = "Cruzeiro",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 5,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(89),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 187, DateTimeKind.Local).AddTicks(98),
                            DataFundacao = new DateTime(1908, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "galaodamassa.jpg",
                            NomeTime = "Atletico",
                            TimeAtivo = true
                        });
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(2213),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(2180),
                            Email = "maykontaiorpm@gmail.com",
                            Login = "Maykon1993",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(7167),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(7152),
                            Email = "belbelm@gmail.com",
                            Login = "belcastroic",
                            Senha = "teste@123"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(7257),
                            DataCadastro = new DateTime(2021, 5, 3, 16, 40, 26, 192, DateTimeKind.Local).AddTicks(7252),
                            Email = "santacruz@gmail.com",
                            Login = "santacruzpe451",
                            Senha = "teste@123"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Games")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.HasOne("Dominio.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
