// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210517123421_EResponsavelTime")]
    partial class EResponsavelTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("adversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("dtAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dtCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("psnAdversario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("telefoneAdversario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoJogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 1,
                            adversario = "Tombense",
                            data = "18-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 214, DateTimeKind.Local).AddTicks(6198),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 214, DateTimeKind.Local).AddTicks(6212),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 2,
                            TeamId = 1,
                            adversario = "America",
                            data = "17-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6120),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6122),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 3,
                            TeamId = 1,
                            adversario = "Cruzeiro",
                            data = "17-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6265),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6267),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 4,
                            TeamId = 2,
                            adversario = "Tombense",
                            data = "21-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6289),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6291),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 5,
                            TeamId = 2,
                            adversario = "America",
                            data = "19-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6311),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6313),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 6,
                            TeamId = 2,
                            adversario = "Cruzeiro",
                            data = "19-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6340),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6342),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 7,
                            TeamId = 3,
                            adversario = "Tombense",
                            data = "18-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6363),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6365),
                            dtAdversario = "Zezinho",
                            dtCadastro = "Maykon",
                            horario = "16:30",
                            psnAdversario = "tomtom",
                            telefoneAdversario = "31956785421",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 8,
                            TeamId = 3,
                            adversario = "America",
                            data = "20-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6385),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6387),
                            dtAdversario = "Lisca",
                            dtCadastro = "Isabela",
                            horario = "22:00",
                            psnAdversario = "liscadoid",
                            telefoneAdversario = "31956784321",
                            tipoJogo = "Camp. Mineiro"
                        },
                        new
                        {
                            Id = 9,
                            TeamId = 3,
                            adversario = "Cruzeiro",
                            data = "20-05-2021",
                            dataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6406),
                            dataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(6408),
                            dtAdversario = "Felipe",
                            dtCadastro = "Ramiro",
                            horario = "16:00",
                            psnAdversario = "conception",
                            telefoneAdversario = "38991081254",
                            tipoJogo = "Camp. Mineiro"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PerfilPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PlayerAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("PosicaoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicaoP")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(9119),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(9105),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maykon",
                            Numero = 13,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "Maykon1993",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(86),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(76),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Samuel",
                            Numero = 7,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Meia Atacante",
                            Psn = "santacruzpe",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(291),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(288),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Celio",
                            Numero = 99,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "Celio_Shadow_14",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(308),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(306),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jose",
                            Numero = 3,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Atacante",
                            Psn = "joselito1970",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(322),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(319),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mauricio",
                            Numero = 4,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Volante",
                            PosicaoP = "Goleiro",
                            Psn = "maumau",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(345),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(343),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando",
                            Numero = 6,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Meia Atacante",
                            Psn = "fernando123",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(358),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(356),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Adam",
                            Numero = 2,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "Lateral",
                            PosicaoP = "Zagueiro",
                            Psn = "adao",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(372),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(370),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Emerson",
                            Numero = 5,
                            PerfilPlayer = "DT",
                            PlayerAtivo = true,
                            PosicaoA = "Atacante",
                            PosicaoP = "Volante",
                            Psn = "emer",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(385),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 218, DateTimeKind.Local).AddTicks(383),
                            DataNascimento = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jullius",
                            Numero = 9,
                            PerfilPlayer = "Jogador",
                            PlayerAtivo = true,
                            PosicaoA = "agueiro",
                            PosicaoP = "Atacante",
                            Psn = "cachaca",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuraTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psn")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayersApp");
                });

            modelBuilder.Entity("Dominio.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GamePes")
                        .HasColumnType("bit");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("TimeAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 203, DateTimeKind.Local).AddTicks(4447),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 210, DateTimeKind.Local).AddTicks(3861),
                            DataFundacao = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(1881),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2041),
                            DataFundacao = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2141),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2163),
                            DataFundacao = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 4,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2169),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2181),
                            DataFundacao = new DateTime(1924, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = false,
                            LinkEscudo = "cruzeirocaiu.jpg",
                            NomeTime = "Cruzeiro",
                            TimeAtivo = true
                        },
                        new
                        {
                            Id = 5,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2186),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 211, DateTimeKind.Local).AddTicks(2196),
                            DataFundacao = new DateTime(1908, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GamePes = true,
                            LinkEscudo = "galaodamassa.jpg",
                            NomeTime = "Atletico",
                            TimeAtivo = true
                        });
                });

            modelBuilder.Entity("Dominio.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("ResponsavelTime")
                        .HasColumnType("bit");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(9523),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 215, DateTimeKind.Local).AddTicks(9510),
                            Email = "maykontaiorpm@gmail.com",
                            Login = "Maykon1993",
                            ResponsavelTime = true,
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(4390),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(4377),
                            Email = "belbelm@gmail.com",
                            Login = "belcastroic",
                            ResponsavelTime = false,
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(4461),
                            DataCadastro = new DateTime(2021, 5, 17, 9, 34, 20, 216, DateTimeKind.Local).AddTicks(4459),
                            Email = "santacruz@gmail.com",
                            Login = "santacruzpe451",
                            ResponsavelTime = false,
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Game", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Games")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("Dominio.Models.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("Dominio.Models.Player", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
