// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Psn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "31993712719",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(7540),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(7525),
                            Nome = "Maykon",
                            Numero = 13,
                            Psn = "Maykon1993",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(6674),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(6641),
                            Nome = "Samuel",
                            Numero = 7,
                            Psn = "santacruzpe",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Celular = "44967543245",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7170),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7157),
                            Nome = "Celio",
                            Numero = 9,
                            Psn = "Celio_Shadow_14",
                            TimeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Celular = "31993122719",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7197),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7189),
                            Nome = "Jose",
                            Numero = 5,
                            Psn = "joselito1970",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Celular = "11978653211",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7219),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7210),
                            Nome = "Mauricio",
                            Numero = 6,
                            Psn = "maumau",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Celular = "44967542145",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7259),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7250),
                            Nome = "Fernando",
                            Numero = 10,
                            Psn = "fernando123",
                            TimeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Celular = "31993154719",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7280),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7272),
                            Nome = "Adam",
                            Numero = 2,
                            Psn = "adao",
                            TimeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Celular = "11978113211",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7300),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7293),
                            Nome = "Emerson",
                            Numero = 8,
                            Psn = "emer",
                            TimeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Celular = "44961242145",
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7321),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 756, DateTimeKind.Local).AddTicks(7313),
                            Nome = "Jullius",
                            Numero = 3,
                            Psn = "cachaca",
                            TimeId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Models.PlayerPosicao", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "PosicaoId");

                    b.HasIndex("PosicaoId");

                    b.ToTable("PlayersPosicoes");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PosicaoId = 7
                        },
                        new
                        {
                            PlayerId = 1,
                            PosicaoId = 5
                        },
                        new
                        {
                            PlayerId = 2,
                            PosicaoId = 6
                        },
                        new
                        {
                            PlayerId = 3,
                            PosicaoId = 11
                        },
                        new
                        {
                            PlayerId = 4,
                            PosicaoId = 3
                        },
                        new
                        {
                            PlayerId = 5,
                            PosicaoId = 2
                        },
                        new
                        {
                            PlayerId = 6,
                            PosicaoId = 5
                        },
                        new
                        {
                            PlayerId = 7,
                            PosicaoId = 9
                        },
                        new
                        {
                            PlayerId = 8,
                            PosicaoId = 10
                        },
                        new
                        {
                            PlayerId = 9,
                            PosicaoId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            PosicaoId = 7
                        },
                        new
                        {
                            PlayerId = 3,
                            PosicaoId = 7
                        });
                });

            modelBuilder.Entity("Dominio.Models.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomePosicao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posicoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomePosicao = "Goleiro"
                        },
                        new
                        {
                            Id = 2,
                            NomePosicao = "Lateral Direito"
                        },
                        new
                        {
                            Id = 3,
                            NomePosicao = "Zagueiro"
                        },
                        new
                        {
                            Id = 4,
                            NomePosicao = "Lateral Esquerdo"
                        },
                        new
                        {
                            Id = 5,
                            NomePosicao = "Volante"
                        },
                        new
                        {
                            Id = 6,
                            NomePosicao = "Meia Ligação"
                        },
                        new
                        {
                            Id = 7,
                            NomePosicao = "Meia Atacante"
                        },
                        new
                        {
                            Id = 8,
                            NomePosicao = "Ponta Esquerda"
                        },
                        new
                        {
                            Id = 9,
                            NomePosicao = "Ponta Direita"
                        },
                        new
                        {
                            Id = 10,
                            NomePosicao = "Segundo Atacante"
                        },
                        new
                        {
                            Id = 11,
                            NomePosicao = "Centro Avante"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkEscudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 754, DateTimeKind.Local).AddTicks(8903),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 752, DateTimeKind.Local).AddTicks(6465),
                            LinkEscudo = "link.huntersx.jpg",
                            NomeTime = "Huntersx"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(5775),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(5746),
                            LinkEscudo = "link.bleuz.jpg",
                            NomeTime = "Bleuz"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(5897),
                            DataCadastro = new DateTime(2021, 4, 20, 21, 11, 52, 755, DateTimeKind.Local).AddTicks(5895),
                            LinkEscudo = "link.mastermaq.jpg",
                            NomeTime = "Mastermaq"
                        });
                });

            modelBuilder.Entity("Dominio.Models.Player", b =>
                {
                    b.HasOne("Dominio.Models.Time", "Time")
                        .WithMany("Players")
                        .HasForeignKey("TimeId");
                });

            modelBuilder.Entity("Dominio.Models.PlayerPosicao", b =>
                {
                    b.HasOne("Dominio.Models.Player", "Player")
                        .WithMany("PlayerPosicoes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Models.Posicao", "Posicao")
                        .WithMany("PlayerPosicoes")
                        .HasForeignKey("PosicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
